'''DO NOT UNDER ANY CIRCUMSTANCES PUSH THIS FILE TO GITHUB AFTER YOU HAVE PUT YOUR API KEY INTO IT
   NOT ONLY WILL YOU BE CHASTISED, BUT THERE ARE BOTS OUT THERE LOOKING FOR API KEYS'''

'''MAKE CERTAIN TO ADD THIS FILE TO YOUR PRIVATE GITIGNORE FILE.'''

secret_key = '4ylN8OWi1dhG5Yhq3PQstA'
